kind: "AppHostingBackend"
apiVersion: "v1alpha"

# ビルド設定
buildSettings:
  cpu: 1
  memoryMiB: 512
  minInstances: 0
  maxInstances: 10

# 実行時の設定
runSettings:
  cpu: 1
  memoryMiB: 512
  minInstances: 0
  maxInstances: 10
  # Secret Managerから環境変数を注入（デプロイ後にコンソール等でSecretの作成が必要）
  secrets:
    - variable: GOOGLE_GENERATIVE_AI_API_KEY
      secret: google_generative_ai_api_key
